# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Gothic spellchecker"
got = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Gothic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
got = "TRANSLATE: A spellchecker for Gothic, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.got"

[windows]
system_product_code = "{AFA56467-151D-4C98-BE23-EA5A5D0FAC52}_is1"

[package.speller]
name = "Gothic"
version = "0.1.0"

[package.grammar]
name = "Gothic"
version = "0.1.0"

[package.tts-text-proc]
name = "Gothic"
version = "0.1.0"

[package.hyphenator]
name = "Gothic"
version = "0.1.0"
