template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "goth1244"
__REPO__ = "lang-got"
__UND2C__ = "got"
__UNDEFINED__ = "Gothic"
__UND__ = "got"
